const results=[];
const check=(name, condition)=>{results.push({name,passed:!!condition}); if(!condition) throw new Error('Falhou: '+name);};
const tick=()=>new Promise(r=>setTimeout(r,50));
check('login inicial', !$('loginScreen').hidden && $('appScreen').hidden);
$('email').value='teste@exemplo.com'; $('password').value='teste-local';
await handleLogin({preventDefault(){},stopPropagation(){}});
await tick();
check('login → dashboard', !$('appScreen').hidden && !$('homeScreen').hidden);
check('uma interface de venda',document.querySelectorAll('#salePaymentMethod').length===1 && document.querySelectorAll('#saleFormMessage').length===1 && $('saleModal').querySelectorAll('h2').length===1);
check('quatro atalhos SVG',document.querySelectorAll('.quick-action svg').length===4);
check('cadastros separados',!$('productsScreen').contains($('categoriesList')) && $('settingsScreen').contains($('colorsList')));
check('fotos sem duplicação em cargas paralelas', productImagesCache.p1.length===1);
check('atividade recente',document.querySelectorAll('#recentActivity .activity-item').length>0);
check('pagamentos antigos',formatPaymentMethod('Dinheiro')==='Dinheiro' && normalizePaymentMethod('Cartão de crédito')==='credit_card');
check('data local noturna',localDateKey(new Date(2026,8,20,23,30).toISOString()) === '2026-09-20');
check('data sem horário não muda dia',formatLocalDate('2026-09-20')==='20/09/2026');
check('data ausente',localDateKey(null)==='');
await loadStock();
check('estoque somente operacional',getOperationalVariants().length===3 && Number($('stockTotal').textContent)===9);
$('stockSearch').value='Rosa';filterStock({target:$('stockSearch')});
check('busca exclui inativas e produto inativo',document.querySelectorAll('#stockList .stock-card').length===2 && !$('stockList').textContent.includes('99'));
$('stockSearch').value='';renderStock();
currentFinancePeriod='today';updateFinanceView();
for (const period of ['7days','30days','month']) { currentFinancePeriod=period; check('período '+period,!getFinanceTransactionsForPeriod().some(x=>x.id==='f3')); }
currentFinancePeriod='all';check('todo o histórico',getFinanceTransactionsForPeriod().length===3);currentFinancePeriod='today';
check('filtro financeiro',getFinanceTransactionsForPeriod().length===2 && !$('financeList').textContent.includes('Receita antiga'));
$('financeSearch').value='Embalagens';renderFinance();
check('busca financeira no período',document.querySelectorAll('.finance-card').length===1);
$('financeSearch').value='';currentFinancePeriod='month';updateFinanceView();
showSection('products');await tick();$('newProductButton').focus();openProductModal();await tick();
check('título novo',document.querySelector('#productModal [data-modal-title]').textContent==='Novo produto');
check('fundo inerte',$('appScreen').inert);
const last=$('productModal').querySelector('button[type="submit"]');last.focus();
document.dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',bubbles:true,cancelable:true}));
check('foco contido',document.activeElement.classList.contains('modal-close'));
document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
check('Escape e devolução de foco',$('productModal').hidden && document.activeElement===$('newProductButton') && !$('appScreen').inert);
await loadProductForEdit(productsCache.find(x=>x.id==='p1'));
check('título edição',document.querySelector('#productModal [data-modal-title]').textContent==='Editar produto');
check('draft omite inativa',productVariationsDraft.length===2);
removeProductVariation(0);
const submit=$('productForm').querySelector('button[type="submit"]');
await saveProduct({preventDefault(){},submitter:submit});
check('remoção desativa e preserva',mockDB.product_variants.find(x=>x.id==='v1').is_active===false && mockDB.product_variants.some(x=>x.id==='v1'));
await loadProductForEdit(productsCache.find(x=>x.id==='p1'));
$('productVariationColor').value='pink';$('productVariationSize').value='size-p';$('productVariationQuantity').value='8';addProductVariation();
check('reativação reutiliza identificador',productVariationsDraft.some(x=>x.variantId==='v1'));
await saveProduct({preventDefault(){},submitter:submit});
check('reativação não duplica',mockDB.product_variants.filter(x=>x.product_id==='p1'&&x.color_id==='pink'&&x.size_id==='size-p').length===1 && mockDB.product_variants.find(x=>x.id==='v1').is_active);
await loadProductForEdit(productsCache.find(x=>x.id==='p1'));
removeProductVariation(0);
$('productVariationColor').value='pink';$('productVariationSize').value='size-p';$('productVariationQuantity').value='8';addProductVariation();
check('remover/reinserir antes de salvar reutiliza ID',productVariationsDraft.some(x=>x.variantId==='v1'));
mockFailure={table:'product_variants',action:'update'};
await saveProduct({preventDefault(){},submitter:submit});
check('falha na edição não exclui produto',mockDB.products.some(x=>x.id==='p1')&&!mockCalls.some(x=>x.table==='products'&&x.action==='delete'));
check('falha libera formulário para nova tentativa', !productSaving && !$('productForm').inert);
closeModal('productModal');
await deleteProduct('p3');
check('produto com variações não é excluído',mockDB.products.some(x=>x.id==='p3') && lastAlert.includes('variações'));
await toggleProductActive('p3');check('ativar produto',mockDB.products.find(x=>x.id==='p3').is_active===true);
await toggleProductActive('p3');check('desativar remove operações',!getOperationalVariants().some(x=>x.product_id==='p3'));
mockDB.products.push({id:'empty',name:'Cadastro vazio',is_active:false,user_id:mockUser.id});await loadProducts();await deleteProduct('empty');
check('exclusão somente de cadastro vazio inativo',!mockDB.products.some(x=>x.id==='empty'));
await openNewSaleModal();await tick();$('saleAddProductButton').focus();$('saleAddProductButton').click();
check('adicionar não foca busca',!$('saleProductPicker').hidden && document.activeElement===$('saleAddProductButton'));
document.querySelector('[data-sale-select-product="p1"]').click();
check('seletor variação',!$('saleVariantPicker').hidden && !$('saleVariantPicker').textContent.includes('99'));
document.querySelector('[data-sale-select-variant="v1"]').click();
updateSaleItemQuantity(0,2);$('saleDiscountInput').value='10';$('salePaymentMethod').value='pix';
removeSaleItem(0);check('remover item da venda',saleDraft.length===0 && renderSaleSummary().total===0);addSaleVariant('v1');updateSaleItemQuantity(0,2);
check('total com desconto',Math.abs(renderSaleSummary().total-169.8)<0.001);
const nSales=mockDB.sales.length;
mockDB.product_variants.find(x=>x.id==='v1').is_active=false;
await registerSale();
check('venda revalida variação desativada',mockDB.sales.length===nSales && $('saleFormMessage').textContent.includes('desativada'));
mockDB.product_variants.find(x=>x.id==='v1').is_active=true;
await Promise.all([registerSale(),registerSale()]);
check('bloqueio de venda duplicada',mockDB.sales.length===nSales+1);
check('baixa estoque',mockDB.product_variants.find(x=>x.id==='v1').stock_quantity===6);
check('movimento e financeiro',mockDB.inventory_movements.length===1 && mockDB.financial_transactions.some(x=>x.reference_id===mockDB.sales.at(-1).id));
check('venda fecha modal',$('saleModal').hidden && !$('appScreen').inert);
await openNewSaleModal();toggleSaleProductPicker();addSaleVariant('v1');$('salePaymentMethod').value='cash';
const before=mockDB.product_variants.find(x=>x.id==='v1').stock_quantity;
mockFailure={table:'financial_transactions',action:'insert'};
await registerSale();
check('falha financeira reverte venda e estoque',mockDB.product_variants.find(x=>x.id==='v1').stock_quantity===before && mockDB.sales.length===nSales+1);
closeModal('saleModal');
openTransactionModal();$('transactionType').value='expense';$('transactionCategory').value='Loja';$('transactionDescription').value='Material de teste';$('transactionAmount').value='25';$('transactionPaymentMethod').value='cash';
await Promise.all([saveTransaction({preventDefault(){},submitter:$('transactionForm').querySelector('button[type="submit"]')}),saveTransaction({preventDefault(){},submitter:$('transactionForm').querySelector('button[type="submit"]')})]);
check('novo lançamento',mockDB.financial_transactions.filter(x=>x.description==='Material de teste').length===1);
openProductModal();$('productName').value='Produto de teste';$('productSalePrice').value='59.90';
$('productVariationColor').value='pink';$('productVariationSize').value='size-p';$('productVariationQuantity').value='3';addProductVariation();
const canvas=document.createElement('canvas');canvas.width=200;canvas.height=300;
canvas.getContext('2d').fillRect(0,0,200,300);
const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));
handleProductPhotoSelection({target:{files:[new File([blob],'roupa.png',{type:'image/png'}),new File([blob],'detalhe.png',{type:'image/png'})]}});
check('preview de foto',document.querySelectorAll('#productPhotoPreview img').length===2);
const optimized=await optimizeProductImage(productPhotosDraft[0]);
check('otimização imagem',!!optimized);
await saveProduct({preventDefault(){},submitter:submit});
const savedProduct=mockDB.products.find(x=>x.name==='Produto de teste');
check('múltiplas fotos e principal',mockDB.product_images.filter(x=>x.product_id===savedProduct?.id).length===2 && mockDB.product_images.filter(x=>x.product_id===savedProduct?.id && x.is_primary).length===1);
check('produto novo e variação',mockDB.products.some(x=>x.name==='Produto de teste') && mockDB.product_variants.some(x=>x.stock_quantity===3));
openModal('categoryModal');$('categoryModal').click();check('fechamento pelo backdrop',$('categoryModal').hidden);
await handleLogout();check('logout → login',$('appScreen').hidden && !$('loginScreen').hidden);
await showApplication(mockUser);await tick();
// Preserve a populated sale for responsive screenshots.
await openNewSaleModal();addSaleVariant('v1');closeModal('saleModal');
const allIds=[...document.querySelectorAll('[id]')].map(e=>e.id);check('IDs únicos após fluxos dinâmicos',allIds.length===new Set(allIds).size);
check('sem interativos aninhados',!document.querySelector('button button, button a, a button'));
check('sem erros JS não tratados',reviewErrors.length===0);
// Validate service worker behavior with an isolated cache/network implementation.
const workerCode = await (await fetch('/service-worker.js')).text();
const handlers = {};
const cacheData = new Map();
const deleted = [];
const cache = {addAll:async paths=>paths.forEach(path=>cacheData.set(new URL(path,location.origin+'/').href,new Response('cached'))),
    put:async (key,response)=>cacheData.set(key,response),match:async key=>cacheData.get(key)?.clone()};
let offline=false;
new Function('self','caches','fetch',workerCode)(
    {registration:{scope:location.origin+'/'},location:{origin:location.origin},addEventListener:(name,fn)=>handlers[name]=fn,skipWaiting(){},clients:{claim:async()=>{}}},
    {open:async()=>cache,keys:async()=>['mabijufit-v4','another-app'],delete:async name=>deleted.push(name)},
    async()=>{if(offline) throw new Error('offline');return new Response('network');}
);
let pending;
handlers.install({waitUntil:p=>pending=p});await pending;
check('PWA pré-cache local',cacheData.has(location.origin+'/index.html') && cacheData.has(location.origin+'/js/app.js'));
handlers.activate({waitUntil:p=>pending=p});await pending;
check('PWA preserva caches de outras aplicações',deleted.join(',')==='mabijufit-v4');
offline=true;
let response;
handlers.fetch({request:new Request(location.origin+'/css/style.css'),respondWith:p=>response=p,waitUntil(){}});
check('PWA fallback offline local',await (await response).text()==='cached');
response=null;
handlers.fetch({request:new Request('https://example.test/auth'),respondWith:p=>response=p});
check('PWA ignora serviços externos',response===null);
return JSON.stringify(results,null,2);
